### ISSUE TITLE
ticker showing zoomed in and not visible.

### ISSUE THREAD

**Issue by davehorner** [taoteh1221/Open_Crypto_Tracker#121]
Thanks for the software!

I found that it worked well for some time, I'm not sure what happened but now it is displaying only a portion of the text, which is all zoomed in.

It displays for a second where I can see most things:
<img width="728" alt="image" src="https://github.com/taoteh1221/Open_Crypto_Tracker/assets/140924/d5345c08-693c-409d-bfa0-07d75b5c6548">

Then I am zoomed way in and there is a scrollbar on the right side which I can use to scroll up and down, all the content is there.
<img width="572" alt="image" src="https://github.com/taoteh1221/Open_Crypto_Tracker/assets/140924/db26695c-4c89-48fd-a886-5d694af03351">

I am seeing this behavior on the HDMI and using RealVNC.  I have changed the config to add some coins and flip the orientation.

I am using firefox and using Raspbian.

Or I should say the output indicates it is using firefox, but as you can see from my screen shot above, it looks like google is being used.
```
./ticker-start
server does not have extension for -dpms option
unclutter: someone created a sub-window to my sub-window! giving up
 
Browser not specified, using default browser firefox...
```

**Comment by davehorner** [comment]
I'm sorry I totally meant to place this on https://github.com/taoteh1221/Slideshow_Crypto_Ticker/issues

**Comment by davehorner** [comment]
sorry about that

**Comment by taoteh1221** [comment]
> sorry about that

No worries, I'm checking out this issue on the other repo now.
