### ISSUE TITLE
Please include Yahoo Finance API

### ISSUE THREAD

**Issue by s1-ranjan** [taoteh1221/Open_Crypto_Tracker#169]
I found this article @ https://algotrading101.com/learn/yahoo-finance-api-guide/, it would be nice if Yahoo Finance API could be included in this platform too, please include Yahoo Finance API with this platform.

**Comment by taoteh1221** [comment]
That's NOT an official API. They scrape Yahoo's website, which may violate Yahoo Terms of use. Sorry, this isn't a good idea, from a legal OR technical standpoint.
