### ISSUE TITLE
Extend support for sending alerts in telegram groups and channel's.

### ISSUE THREAD

**Issue by s1-ranjan** [taoteh1221/Open_Crypto_Tracker#20]
As of now it's possible to receive alerts in the telegram bot, but in order to send messages in the groups and channels is not an easy task, so it would be nice if this tracer is able to push the notifications in the group and channels

**Comment by taoteh1221** [comment]
Not sure if this is possible, but I'll look into it in October when I'm working on this project again (on vacation right now from my free software projects).

**Comment by s1-ranjan** [comment]
I found [tgcf ](https://github.com/aahnik/tgcf) on Github, maybe this can do this work, please have a look or there can be some good alternative for this work...

**Comment by taoteh1221** [comment]
Not sure when I'll get to determining the feasibility of enhancing current telegram capabilities. Honestly there are a lot more backlogged things that are way more important than this, and my time is limited these days on my open source / free software projects. I'll check it out at some point when I have prioritized time available.

**Comment by taoteh1221** [comment]
I don't think this is feasible for me to create myself in the core app. However, as of the latest version of this app, there is now full plugin support and developer documentation, so you can build this yourself as a plugin:

https://raw.githubusercontent.com/taoteh1221/Open_Crypto_Tracker/main/DOCUMENTATION-ETC/PLUGINS-README.txt
