### ISSUE TITLE
Getting updates for new coins listing and delisting via email, telegram, and other means.

### ISSUE THREAD

**Issue by s1-ranjan** [taoteh1221/Open_Crypto_Tracker#37]
It would be a great feature if this application can trigger a message for listing and delisting of coins from any exchange, this can help in making a quick modifications in the config file.

**Comment by taoteh1221** [comment]
This doesn't have enough feasibility in my opinion to devote time on adding as a feature. Over-complicating an app leaves users confused on how to use it in the first place. Please review the contributing guidelines before submitting new issues from here onwards: https://raw.githubusercontent.com/taoteh1221/Open_Crypto_Tracker/main/CONTRIBUTING.txt Thanks very much for your feedback.
