### ISSUE TITLE
Support for Pretty links

### ISSUE THREAD

**Issue by s1-ranjan** [taoteh1221/Open_Crypto_Tracker#38]
As of now, the URLs used to show index.php in the URLs which does not look good, so implementing Pretty links can remove the unwanted .PHP part from the URL.

**Comment by taoteh1221** [comment]
I have a lot more things to do to this app that are way more important than hiding index.php in the browser location bar, and very little time these days to do it. Sorry, this isn't a feasible use of my work time on this project.
