### ISSUE TITLE
A feature request for crypto-crypto price alert notification (instead of just fiat value)

### ISSUE THREAD

**Issue by s1-ranjan** [taoteh1221/Open_Crypto_Tracker#44]
There is no issue with the crypto to fiat currency notification as we get all the information in those two variables i.e., in crypto and fiat currency as shown below:
The BAT trade value in the BTC market at the Poloniex exchange has decreased -20.21% in INR value to ₹32.92 over the past 0.05 days since the last price alert. 24 hour pair volume has decreased -4.84% to a INR value of ₹28,762 (volume filter on).
The issue arises when we are trying to get a notification from crypto-crypto exchange information it would be nice if we can get the following  type of notification:
The BAT trade value in the BTC market at the Poloniex exchange has decreased -20.21% in INR value to ₹32.92 or 0.00001381 BTC over the past 0.05 days since the last price alert. 24 hour pair volume has decreased by -4.84% to an INR value of ₹28,762 (volume filter on).
It would be nice if the price of the crypto-crypto also includes the value of crypto in trade value as well as in fiat value i.e.,**₹32.92 or 0.00001381 BTC** as shown in the above example.

**Comment by taoteh1221** [comment]
This price alert feature was NOT designed to show the crypto value, EVEN for crypto market pairings. It is only designed to show the fiat value for ANY pairing (crypto or non-crypto). See the 'help' tab in the app, or README.txt for more information on the price alert feature. 

I'm sorry but I don't see enough feasibility in this feature request to spend my time building it. I don't have much free time these days to add features to this app, and the current price alert features are good enough in my opinion.

**Comment by taoteh1221** [comment]
Have you tried enabling the 'price-target-alert' plugin? This is a way to track and get comm alerts based off crypto value, that is already a feature. See it's activation setting right after the charts section in config.php. 

Additionally, it has it's own config file inside it's plugin folder, within the main subdirectory 'plugins', where you add your market pairs and exchange name, and target price (you MUST use the EXACT exchange markets pairing, there is no fiat conversion).

**Comment by taoteh1221** [comment]
Another consideration is over-complicating features, making them more confusing to use. Sometimes less is more. Make sure to review the contributing guidelines for this project here, to have a sense of what it's trying to accomplish:

https://raw.githubusercontent.com/taoteh1221/Open_Crypto_Tracker/d25aae7e56a013e31aad2d61a2edadc8a0d1e7de/CONTRIBUTING.txt
